### ISSUE TITLE
Re-image undercloud host with RHEL 8.2 for OSP 16.1

### ISSUE THREAD

**Issue by smalleni** [redhat-performance/jetpack#191]
OSP 16 it has to be RHEL 8.1.

**Comment by smalleni** [comment]
@pradiptapks Any update here? Should be a relatively straightforward patch.

**Comment by pradiptapks** [comment]
After review the below task, I think the end goal is to get the RHEL OS version and use it to provision Director node via hammer.
https://github.com/redhat-performance/jetpack/blob/master/setup_undercloud.yml#L31-L34

After playing with ansible ternary, I think the below condition may help to suffice the reimaging 16.1 with RHEL8.2. I need some time to do the further with my bandwidth.

`os_install: "{{ (((osp_release|int > 16) and (rhel_version is version('8.1', '<')))|ternary('RHEL 8.2',	((osp_release|int > 14) and (rhel_version is version('8.0', '<')))|ternary('RHEL 8.1', ((osp_release|int < 15) and (rhel_version is version ('8.0', '>=')))|ternary('RHEL 7.7', false)))) }}"`

I think the above ^^ condition is more complex to me if we plan to test the OSP13 & OSP10 z stream. Bcz RHEL minor version is a key role when we plan to do some specific OSP z stream deployment. If we put variable of RHEL version in global env "group_vars/all.yml" file and use the value to provision Director node, what could be the issue, please help me to understand.

```
        - name: update host to install new os
          shell: hammer -u {{ cloud_name }} -p {{ chassis_password }}  host update --name {{ undercloud_hostname }} --build 1 --operatingsystem '{{ os_install }}' --overwrite 1
          delegate_to: "{{ hammer_host }}"
          vars:
            ansible_user: root
            ansible_python_interpreter: "{{ python_interpreter }}"
```

But from user perspective, it could help get the proper RHEL version as per OSPz stream recommendation.

Please feel free to share your thoughts and correct me if there is any dependency get break.
