### ISSUE TITLE
Issue during overcloud deployment on 1029u scale lab systems

### ISSUE THREAD

**Issue by sanjaychari** [redhat-performance/jetpack#415]
While running `ansible-playbook -vvv main.yml -t overcloud` on 1029u scale lab systems, the following error occurs.
```
TASK [set vm's host ip] ********************************************************
task path: /var/lib/jenkins/.infrared/plugins/tripleo-overcloud/tasks/add_overcloud_host.yml:57
fatal: [undercloud]: FAILED! => {
    "msg": "The conditional check '(node_info.name != baremetal_name) and ((hostvars[node_info.name].ansible_ssh_common_args is defined) and (host
vars[item].ansible_host in hostvars[node_info.name].ansible_ssh_common_args))' failed. The error was: error while evaluating conditional ((node_info.name != baremetal_name) and ((hostvars[node_info.name].ansible_ssh_common_args is defined) and (hostvars[item].ansible_host in hostvars[node_i$fo.name].ansible_ssh_common_args))): \"hostvars['hypervisor']\" is undefined\n\nThe error appears to be in '/var/lib/jenkins/.infrared/plugins/tr$pleo-overcloud/tasks/add_overcloud_host.yml': line 57, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: set vm's host ip\n  ^ here\n"
}
```
The task where it fails is here.
```
- name: set vm's host ip
  set_fact:
      hypervisor_ip: "{{ hostvars[item].ansible_host }}"
  when: "(node_info.name != baremetal_name) and ((hostvars[node_info.name].ansible_ssh_common_args is defined) and (hostvars[item].ansible_host i$
  with_items: "{{ hypervisor_group }}"
```
It appears that infrared is expecting a hypervisor hosts group entry in the active hosts file, but this error doesn't seem to occur on other hardware types in scale lab.
